### ISSUE TITLE
AttributeError when starting transcode

### ISSUE THREAD

**Issue by mbudde** [danielgtaylor/arista#1]
Trying to transcode a DVD I get the following error:
    [...]
    ERROR: block code look-up failed
    ERROR: block code look-up failed
    ERROR: block code look-up failed
    ERROR: block code look-up failed
    Didn't get subframe DSYNC
    Traceback (most recent call last):
      File "/home/devel/forked/arista/arista/transcoder.py", line 145, in _got_info
        self._setup_pass()
      File "/home/devel/forked/arista/arista/transcoder.py", line 348, in _setup_pass
        for x in range(self.info.videocaps.get_size()):
    AttributeError: 'dict' object has no attribute 'get_size'
Arista trunk f3544a634ad770d7fbbeefd4914bfa4121a9b6ef on Ubuntu 9.10

**Comment by mbudde** [comment]
Hmm... I can't reproduce the bug now.

**Comment by danielgtaylor** [comment]
Neither can I... strange. It appears GStreamer handed you a dictionary instead of the object it should have for the videocaps, but I'm not sure what can make that happen. Please try to confirm and reproduce and let me know the exact steps to do so!

**Comment by sadsky** [comment]
Hi Daniel, I get similar problem.
Was trying to transcode .mkv encapsulated h264 HD stream to iPod.

File "/usr/lib/python2.6/dist-packages/arista/transcoder.py", line 145, in _got_info
    self._setup_pass()
  File "/usr/lib/python2.6/dist-packages/arista/transcoder.py", line 348, in _setup_pass
    for x in range(self.info.videocaps.get_size()):
AttributeError: 'dict' object has no attribute 'get_size'
Traceback (most recent call last):
  File "/usr/bin/arista-gtk", line 854, in on_remove
    self.stop_processing_entry(entry)
  File "/usr/bin/arista-gtk", line 833, in stop_processing_entry
    source = entry.transcoder.pipe.get_by_name("source")
AttributeError: 'NoneType' object has no attribute 'get_by_name'
