### ISSUE TITLE
Create Conversion button not responding in 11.10

### ISSUE THREAD

**Issue by andyfriedl** [danielgtaylor/arista#109]
Unable to get a response from the Create Conversion button. The other buttons (presets, preferences) work. 

More info: All apps seem to be working after 11.10 upgrade. All other media apps work. I also re-installed arista in synaptic package manager. 

Trying to think of everything to include.

**Comment by rechever** [comment]
same problem...
using arista 0.9.7
transmageddon ok

**Comment by ak4me** [comment]
Arista will not Create a Conversion for me. The button is also not responding. I have Ubuntu 11.10 64bit.
I launched the artista-gtk from the command line to get more error information and this is what I see.

blank@none:~$ sudo arista-gtk 
Traceback (most recent call last):
  File "/usr/bin/arista-gtk", line 514, in on_add
    self.add_dialog = AddDialog(self, selected_preset)
  File "/usr/bin/arista-gtk", line 1063, in **init**
    self.setup_source()
  File "/usr/bin/arista-gtk", line 1138, in setup_source
    model.set_value(iter, 0, theme.load_icon(icon, size, 0))
glib.GError: Icon 'gtk-cdrom' not present in theme

is there anyway to get this gtk-cdrom icon loaded in the theme or do you think that won't fix it?

Thanks,
Clint

**Comment by andyfriedl** [comment]
blank@none:~$ sudo arista-gtk 

Traceback (most recent call last):
  File "/usr/bin/arista-gtk", line 514, in on_add
    self.add_dialog = AddDialog(self, selected_preset)
  File "/usr/bin/arista-gtk", line 1063, in **init**
    self.setup_source()
  File "/usr/bin/arista-gtk", line 1145, in setup_source
    size, 0))
glib.GError: Icon 'camera-video' not present in theme
^CTraceback (most recent call last):

**Comment by Advix** [comment]
Install gnome-icon-theme-full package solves the problem.
https://bugs.launchpad.net/ubuntu/+source/arista/+bug/875772

**Comment by ak4me** [comment]
Thank you for the follow up!

That fixed the problem with Arista and some other non-related problems I 
had!

-Clint

**Comment by andyfriedl** [comment]
Thanks you for this fix. I tried other transcoders while waiting for a fix and this is by far the best out there. Thanks!

**Comment by robvdl** [comment]
I had this issue on Kubuntu too, which uses the Oxygen icon theme and "gtk-cdrom" doesn't appear to be present in this icon theme.

I had to install the tango icon theme packages and temporarily switch to the tango icon theme to run the app, then back to oxygen when done.

You shouldn't be using "gtk-cdrom" it is too specific, but rather use standard freedesktop.org names:

http://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html

The proper name appears to be "drive-optical" instead of "gtk-cdrom"

**Comment by SA0TAY** [comment]
Moreover, it should fallback on some generic icon if it can't find its preferred one, not just cease functioning.

**Comment by danielgtaylor** [comment]
I am using gtk.STOCK_CDROM as the icon name, which should point to the correct string. Is this an upstream issue or does it make sense to just update the name to 'drive-optical' for now?
