### ISSUE TITLE
Cannot open conversion window

### ISSUE THREAD

**Issue by monreal** [danielgtaylor/arista#116]
When I press the "Create Conversion" button nothing happens. I get this on the console:

$ ./arista-gtk 
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
Traceback (most recent call last):
  File "./arista-gtk", line 515, in on_add
    self.add_dialog = AddDialog(self, selected_preset)
  File "./arista-gtk", line 1209, in **init**
    self.setup_source()
  File "./arista-gtk", line 1285, in setup_source
    model.set_value(iter, 0, theme.load_icon(icon, size, 0))
glib.GError: Icon 'gtk-cdrom' not present in theme

This is on Fedora 16 with GTK 2.24.7... strange; gtk-cdrom should be supported according to http://developer.gnome.org/gtk/2.24/gtk-Stock-Items.html#GTK-STOCK-CDROM:CAPS

**Comment by te-con-miel** [comment]
Hello,

In Ubuntu 11.10 I have the same problem, only in the 64 bits version, in the 32 bits system work well.

**Comment by TheWattsMan** [comment]
I just had success in fixing this issue in Fedora 15 x64 by resetting the presets (Preferences>reset presets). Dunno if my console readout was the same, as I wasn't running it in the console, but maybe it was the same issue.

**Comment by monreal** [comment]
This didn't help me

**Comment by lgedmitri** [comment]
resetting the presets worked for me. It also unchecks "Search for optical drives..."(or smth like that) option, so probably this was the problem, because I'm working on netbook and I haven't got any optical drives

**Comment by monreal** [comment]
Alright, uncheking that finally helped. But the preset reset does not do this automatically

**Comment by lgedmitri** [comment]
Well, maybe I did this by myself and didn't noticed that :)
