### ISSUE TITLE
Arista/Transcoder does not work with Fluendo CODEC pack installed

### ISSUE THREAD

**Issue by pmlopes** [danielgtaylor/arista#151]
If I install the fluendo codec pack to better playback support, when trying to convert a video say from my HD camera to some other format to share with my family, there is a crash while trying to decode the original width/height and video caps.

I have no experience with gstreamer and after digging on the internet i found this site with and example of code that correctly extracts the width and height:

http://blogs.gnome.org/uraeus/2011/01/17/back-on-transmageddon-and-new-gstreamer-features/

I also raised a question with fluendo about the metadata but up to now i have now answer yet.

**Comment by danielgtaylor** [comment]
Interesting. I'm actually using the python version of the discoverer. Can you run with arista-gtk -v and paste in any output of the errors?

**Comment by pmlopes** [comment]
paulo@jetdrone:~$ arista-gtk -v
arista.presets [517]: DEBUG Loaded device DVD Player (3 presets)
arista.presets [517]: DEBUG Loaded device Web Browser (3 presets)
arista.presets [517]: DEBUG Loaded device Sony Playstation (2 presets)
arista.presets [517]: DEBUG Loaded device Computer (4 presets)
arista.presets [517]: DEBUG Loaded device Nokia N Series (4 presets)
arista.presets [517]: DEBUG Loaded device Apple iOS (4 presets)
arista.presets [517]: DEBUG Loaded device Android (6 presets)
arista-gtk [2369]: DEBUG Increasing niceness by 5...
arista.queue [185]: DEBUG Found item in queue! Queue is Transcode queue: [Queue entry /home/paulo/Pictures/2013/02/17/2013-02-17-0155.mp4 -> DivX Home Theater avimux -> /home/paulo/Desktop/2013-02-17-0155.avi]
arista.discoverer [230]: DEBUG Discovering /home/paulo/Pictures/2013/02/17/2013-02-17-0155.mp4
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/arista/transcoder.py", line 228, in _got_info
    self._setup_pass()
  File "/usr/lib/python2.7/dist-packages/arista/transcoder.py", line 396, in _setup_pass
    height = int((float(wmin) / owidth) \* oheight)
ZeroDivisionError: float division by zero
arista-gtk [477]: DEBUG Cleaning up and flushing buffers...
paulo@jetdrone:~$

**Comment by pmlopes** [comment]
I've contacted fluendo and they claim that this might work on ubuntu 12.10 and that they will also have a look into the current LTS 12.04.2.

I am planning to try out the 12.10 tomorrow and will post what i can find.

**Comment by pmlopes** [comment]
I've installed 12.10 and I get the same error:

paulo@jetdrone:~$ arista-gtk -v
arista.presets [517]: DEBUG Loaded device Nokia N Series (4 presets)
arista.presets [517]: DEBUG Loaded device Android (6 presets)
arista.presets [517]: DEBUG Loaded device Sony Playstation (2 presets)
arista.presets [517]: DEBUG Loaded device DVD Player (3 presets)
arista.presets [517]: DEBUG Loaded device Web Browser (3 presets)
arista.presets [517]: DEBUG Loaded device Computer (4 presets)
arista.presets [517]: DEBUG Loaded device Apple iOS (4 presets)
arista-gtk [2369]: DEBUG Increasing niceness by 5...
arista.queue [185]: DEBUG Found item in queue! Queue is Transcode queue: [Queue entry /home/paulo/Pictures/2013/02/17/2013-02-17-0155.mp4 -> DivX Home Theater avimux -> /home/paulo/Desktop/2013-02-17-0155.avi]
arista.discoverer [230]: DEBUG Discovering /home/paulo/Pictures/2013/02/17/2013-02-17-0155.mp4
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/arista/transcoder.py", line 228, in _got_info
    self._setup_pass()
  File "/usr/lib/python2.7/dist-packages/arista/transcoder.py", line 396, in _setup_pass
    height = int((float(wmin) / owidth) \* oheight)
ZeroDivisionError: float division by zero
arista-gtk [477]: DEBUG Cleaning up and flushing buffers...
paulo@jetdrone:~$
