### ISSUE TITLE
not provided by any .service files

### ISSUE THREAD

**Issue by emcek** [danielgtaylor/arista#158]
my arista (compiled in gentoo) doesn't transcode when I set conversion: file, destination and device preset and click create, I got: 

```
No accelerated IMDCT transform found 
Traceback (most recent call last): 
  File "/usr/bin/arista-gtk-python2.7", line 665, in on_queue_entry_error 
    notice.show() 
glib.GError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
```

**Comment by danielgtaylor** [comment]
I think you need to install a notifications daemon. I can also try to catch
that error and prevent the crash in the future.

On Wed, Sep 18, 2013 at 3:13 AM, emcek notifications@github.com wrote:

> my arista (compiled in gentoo) doesn't transcode when I set conversion:
> file, destination and device preset and click create, I got:
> 
> No accelerated IMDCT transform found
> Traceback (most recent call last):
>   File "/usr/bin/arista-gtk-python2.7", line 665, in on_queue_entry_error
>     notice.show()
> glib.GError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.Notifications was not provided by any .service files
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/danielgtaylor/arista/issues/158
> .

## 

Daniel G. Taylor
http://programmer-art.org/

**Comment by emcek** [comment]
I have startup-notification-0.12 installed from http://www.freedesktop.org/wiki/Software/startup-notification. What deaom should I install?

**Comment by danielgtaylor** [comment]
I think it's notification-daemon or notify-osd. I seem to have nodify-osd
installed.

On Wed, Sep 18, 2013 at 9:45 AM, emcek notifications@github.com wrote:

> I have startup-notification-0.12 installed from
> http://www.freedesktop.org/wiki/Software/startup-notification. What deaom
> should I install?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/danielgtaylor/arista/issues/158#issuecomment-24680214
> .

## 

Daniel G. Taylor
http://programmer-art.org/

**Comment by emcek** [comment]
I've installed notify-osd and now arista showed me;

```
Traceback (most recent call last):
  File "/usr/bin/arista-gtk-python2.7", line 665, in on_queue_entry_error
    notice.show()
glib.GError: Error calling StartServiceByName for org.freedesktop.Notifications: GDBus.Error:org.freedesktop.DBus.Error.Spawn.ChildSignaled: Process /usr/lib64/notify-osd/notify-osd received signal 5
```

**Comment by danielgtaylor** [comment]
Any luck getting this working? I'm not entirely sure what could be wrong. The Gentoo guys may know more about how to get notify-osd working properly.

**Comment by emcek** [comment]
no much to add, gentoo's forum is silent and I'm trying get to working. IMHO isn't arista issue so if you like you can close it.

**Comment by rahimiarifhussain** [comment]
![the name was not](https://user-images.githubusercontent.com/57014445/73499979-34c03080-43df-11ea-87df-bdf6505cfcec.png)

**Comment by rahimiarifhussain** [comment]
how can solve the problem ?
