### ISSUE TITLE
arista-gtk, Ubuntu 10.04 (lucid), source to mkv/theora/vorbis, arista.transcoder.PipelineException: Unable to construct pipeline! could not link audioresample0 to vorbisenc0

### ISSUE THREAD

**Issue by stevednm** [danielgtaylor/arista#34]
Installed arista using Synaptic in Ubuntu 10.04 (lucid). Inserted DVD to transcode to matroska container / theora video / vorbis audio, using preset "computer" with "normal (patent-free)" setting.

Because I started arista on the command line, I could see the output including error messages. After adding DVD source to queue, these are the messages in the command-line terminal:

libdvdread: Using libdvdcss version 1.2.10 for DVD access

libdvdread: Attempting to retrieve all CSS keys
libdvdread: This can take a _long_ time, please be patient

libdvdread: Get key for /VIDEO_TS/VIDEO_TS.VOB at 0x00000137
libdvdread: Elapsed time 0
libdvdread: Get key for /VIDEO_TS/VTS_01_0.VOB at 0x000001a2
libdvdread: Elapsed time 0
libdvdread: Get key for /VIDEO_TS/VTS_01_1.VOB at 0x0000aa37
libdvdread: Elapsed time 0
libdvdread: Get key for /VIDEO_TS/VTS_02_0.VOB at 0x002bf67d
libdvdread: Elapsed time 0
libdvdread: Get key for /VIDEO_TS/VTS_02_1.VOB at 0x002bf6b6
libdvdread: Elapsed time 0
libdvdread: Get key for /VIDEO_TS/VTS_03_0.VOB at 0x003ae777
libdvdread: Elapsed time 0
libdvdread: Get key for /VIDEO_TS/VTS_03_1.VOB at 0x003ae7b0
libdvdread: Elapsed time 0
libdvdread: Found 3 VTS's
libdvdread: Elapsed time 0
Traceback (most recent call last):
  File "/usr/share/arista/arista/transcoder.py", line 143, in _got_info self._setup_pass()
  File "/usr/share/arista/arista/transcoder.py", line 441, in _setup_pass self._build_pipeline(cmd)
  File "/usr/share/arista/arista/transcoder.py", line 460, in _build_pipeline str(e))
arista.transcoder.PipelineException: Unable to construct pipeline! could not link audioresample0 to vorbisenc0

Thank you for creating such a promising-looking and useful application.
Steve, New Mexico, US

**Comment by danielgtaylor** [comment]
Can you possibly try running arista-transcode -s dvd:///dev/dvd and try converting with arista-gtk --verbose pasting all the output here? Thanks.
