### ISSUE TITLE
Arista doesn't transcode in certain scenarios

### ISSUE THREAD

**Issue by Mikywing** [danielgtaylor/arista#69]
Hi! This is my first time i contribute to the project, I am very interested in Arista (it looks really simple and promising!) but i continuously find some problems that prevent me to correctly convert some videos. I'll start with this one and i'll publish others as soon as they appear. :)

I start arista-gtk 0.9.6 from terminal to convert a 1080p mkv file with the dvd player->divx home theater profile. The conversion doesn't start, and here's the traceback i got from the terminal:
Stream with high frequencies VQ coding
Traceback (most recent call last):
  File "/home/wingman/Scrivania/arista-0.9.6/arista/transcoder.py", line 223, in _got_info
    self._setup_pass()
  File "/home/wingman/Scrivania/arista-0.9.6/arista/transcoder.py", line 375, in _setup_pass
    height = int((float(wmin) / owidth) \* oheight)
ZeroDivisionError: float division

Let me know if you need more infos, and how to get them!
Keep up the good job :)

**Comment by Mikywing** [comment]
I just tried installing the most recent developer's gstreamer packages from ppa:gstreamer-developers/ppa, and the problem disappeared. I'm using Ubuntu 10.04 Lucid Lynx. I guess this is not an Arista problem...
