### ISSUE TITLE
arista-transcode | UnicodeDecodeError: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by esver** [danielgtaylor/arista#81]
I've a problem when I launch :
arista-transcode -i android
I've the following message :

*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
Info profile:

```
                    ID: android
                 Fait : Generic
```

Traceback (most recent call last):
  File "./arista-transcode", line 278, in <module>
    "value": value
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 22: ordinal not in range(128)

I've ubuntu 10.10 in French with utf-8.
When I replace the line 278 with
"value": value.encode('utf-8')

It works and I have the following message :
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
Info profile:

```
                    ID: android
                 Fait : Generic
               Modèle: Android Phone
```

 Copy text       Description: Presets for all known Android phones
                    Auteur: Daniel G. Taylor dan@programmer-art.org
                   Version: 1.4
            Pré réglages: Droid / Milestone, Droid X, Galaxy Spica / GT-I5700 / Galaxy Lite, G1 / Dream, *Samsung Galaxy S, Nexus One / Desire

I think it's a problem of the french accentuated characters.

**Comment by danielgtaylor** [comment]
Fixed in 2fc9bb2, thanks!

**Comment by ildar** [comment]
$ arista-transcode ы.flv 
*\* Message: pygobject_register_sinkfunc is deprecated (GstObject)
Traceback (most recent call last):
  File "/usr/bin/arista-transcode", line 387, in <module>
    to_be_created=outputs, device_name=options.device)
  File "/usr/lib/python2.7/site-packages/arista/utils.py", line 175, in generate_output_path
    default_out = name + "." + preset.extension
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd1 in position 0: ordinal not in range(128)

**Comment by danielgtaylor** [comment]
Thanks for finding that bug - for now just rename your file until I fix this issue in trunk.
